name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main  # Triggers when you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: FTP Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/          # Uploads only the dist folder contents
          server-dir: /   # Directly into your website root -- lets see for test
          dangerous-clean-slate: false